import { AwakeningContent } from "@/types/about/awakening.types";

export const AWAKENING_CONTENT: AwakeningContent = {
  sectionTag: 'INTRODUCTION',
  heading: 'Awakening Learning at the Footsteps of Enlightenment',
  paragraphs: [
    `Just a short distance from Lumbini, the sacred birthplace of Gautama Buddha, Bodhi International Montessori School was founded with a purpose deeper than education alone. Here, learning grows in the quiet presence of history, compassion, and awakening. The word Bodhi means awakening — a moment when wisdom begins to unfold and awareness deepens. Inspired by this idea, our school is not simply a place where children study. It is a space where young minds are gently guided to grow intellectually, emotionally, and morally. From the beginning, our vision has been to create a nurturing and inspiring environment where every child can develop academically, socially, and emotionally. At Bodhi, education is guided by Montessori principles that encourage exploration, independence, and joyful discovery. At the same time, living in the spiritual atmosphere of Lumbini naturally shapes our values. Compassion, mindfulness, humility, and respect for life are quietly woven into everyday learning.`,
    `We believe education is not limited to textbooks. It is about nurturing curiosity, responsibility, and confidence in young minds. Our teachers work closely with children to help them understand ideas deeply while encouraging creativity, critical thinking, and collaboration. Over the years, we have grown into a community built on respect, inclusivity, and trust, where every child feels safe, supported, and motivated to reach their full potential. At Bodhi International Montessori School, learning is a shared journey between school and families. Through strong relationships and open communication, we strive to create an environment where children feel encouraged to explore, grow, and develop a lifelong love for learning. We believe the future needs more than academic success alone. It needs thoughtful, compassionate individuals with clarity and purpose. From this sacred land of beginnings, we continue our journey with a simple commitment: to give every child a strong foundation for life, shaped by knowledge, character, and inner growth.`,
  ],
  closingLine: 'Here, education is not rushed. It is nurtured with care.',
}